Провести дисперсионный анализ для определения того, есть ли различия среднего роста среди взрослых футболистов, хоккеистов и штангистов. Даны значения роста в трех группах случайно выбранных спортсменов: Футболисты: 173, 175, 180, 178, 177, 185, 183, 182. Хоккеисты: 177, 179, 180, 188, 177, 172, 171, 184, 180. Штангисты: 172, 173, 169, 177, 166, 180, 178, 177, 172, 166, 170.

In [1]:
import numpy as np
from scipy import stats

In [2]:
foot = np.array([173, 175, 180, 178, 177, 185, 183, 182])
foot

array([173, 175, 180, 178, 177, 185, 183, 182])

In [3]:
hoc = np.array ([177, 179, 180, 188, 177, 172, 171, 184, 180])
hoc

array([177, 179, 180, 188, 177, 172, 171, 184, 180])

In [4]:
sht = np.array ([172, 173, 169, 177, 166, 180, 178, 177, 172, 166, 170])
sht

array([172, 173, 169, 177, 166, 180, 178, 177, 172, 166, 170])

In [5]:
stats.f_oneway(foot, hoc, sht)

F_onewayResult(statistic=5.500053450812596, pvalue=0.010482206918698693)

In [6]:
stats.f.ppf(0.95, 2, 25)

3.3851899614491683